import { defineConfig } from 'vite';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { readFileSync, readdirSync } from 'fs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

function htmlPartials() {
  return {
    name: 'html-partials',
    transformIndexHtml(html) {
      const header = readFileSync(resolve(__dirname, 'partials/_header.html'), 'utf-8');
      const footer = readFileSync(resolve(__dirname, 'partials/_footer.html'), 'utf-8');
      return html
        .replace('<!--HEADER-->', header)
        .replace('<!--FOOTER-->', footer);
    },
  };
}

// Every *.html file in the project root becomes its own build entry —
// the 6 category pages, the 2 legacy redirect stubs (text.html,
// utilities.html), and the 60+ dedicated per-tool SEO landing pages
// generated by scripts/generate-seo-pages.mjs (e.g. resize-image.html).
// Auto-discovering these means running the generator to add/remove a
// tool page never requires a matching manual edit here.
function discoverHtmlEntries() {
  const entries = {};
  readdirSync(__dirname)
    .filter((name) => name.endsWith('.html'))
    .forEach((name) => {
      const entryName = name === 'index.html' ? 'main' : name.replace(/\.html$/, '');
      entries[entryName] = resolve(__dirname, name);
    });
  return entries;
}

export default defineConfig({
  plugins: [htmlPartials()],
  build: {
    rollupOptions: {
      input: discoverHtmlEntries(),
    },
  },
});
